name: Slapper
author: jojoe77777
version: 7357
description: Rewrite of Slapper
main: slapper\main
api: [1.12.0, 1.13.0]
commands:
  slapper:
    description: Create a slappable entity, or edits an existing one!
    usage: "/slapper [args]..."
    permission: slapper.command
permissions:
  slapper.command:
    description: Allow using /slapper
    default: op